// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtEhGbe3212CwQm3DA5wGZ-qe1yKF4fI4',
    appId: '1:939193095617:web:6fb280b63fef2515404b40',
    messagingSenderId: '939193095617',
    projectId: 'quizish-ee75f',
    authDomain: 'quizish-ee75f.firebaseapp.com',
    databaseURL: 'https://quizish-ee75f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizish-ee75f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb6pCs2Py2o9IHccmNL4x2Xy39CQ83Nzg',
    appId: '1:939193095617:android:26ddd11762488e5f404b40',
    messagingSenderId: '939193095617',
    projectId: 'quizish-ee75f',
    databaseURL: 'https://quizish-ee75f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizish-ee75f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbIU7D7yWJpdWU_05L1XkT9CXRf-qAX3g',
    appId: '1:939193095617:ios:b1df43857f6c66c8404b40',
    messagingSenderId: '939193095617',
    projectId: 'quizish-ee75f',
    databaseURL: 'https://quizish-ee75f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizish-ee75f.appspot.com',
    androidClientId: '939193095617-jgufenjm457u1if8p282e2l5s8ts0oij.apps.googleusercontent.com',
    iosClientId: '939193095617-2ok35a5h6bpgaqvfcvm72j5g7sg99ai4.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbIU7D7yWJpdWU_05L1XkT9CXRf-qAX3g',
    appId: '1:939193095617:ios:b1df43857f6c66c8404b40',
    messagingSenderId: '939193095617',
    projectId: 'quizish-ee75f',
    databaseURL: 'https://quizish-ee75f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizish-ee75f.appspot.com',
    androidClientId: '939193095617-jgufenjm457u1if8p282e2l5s8ts0oij.apps.googleusercontent.com',
    iosClientId: '939193095617-2ok35a5h6bpgaqvfcvm72j5g7sg99ai4.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizish',
  );
}
